  name: Java CD with Gradle

  on:
    workflow_dispatch:
    release:
      types:
        - published

  jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build
      - name: Publish with gradle
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_NAME }}
          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
          RELEASE: true